### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by lennons301** [cloudera/dbt-hive#101]
Hi attempting to `pip install dbt-hive` on Windows 10

Unable to install the `kerberos` dependency

Initial error `error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools":`

With latest Build Tools then installed a more specific error:

```
fatal error C1083: Cannot open include file: 'gssapi/gssapi.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kerberos
  Running setup.py clean for kerberos
Failed to build kerberos
```

**Comment by niteshy** [comment]
It is fixed as part of https://github.com/cloudera/dbt-hive/pull/119. Will be released next week on 1.4.0 release
