### ISSUE TITLE
Question: multi-threads option support?

### ISSUE THREAD

**Issue by hurcy** [cloudera/dbt-hive#72]
Do you have plans to support multi-threading options in profiles.yml?

**Comment by TapasSenapati** [comment]
Its already supported. Just enable threads:x

`
dbt_hive_demo:
  outputs:
    dev_cia_cdp:
      auth_type: ldap
      host: hostname
      http_path: path
      password: pwd
      port: 443
      schema: dbt_hive_demo
      threads: n
      type: hive
      use_http_transport: true
      use_ssl: true
      username: name
  target: dev_cia_cdp
`
