### ISSUE TITLE
Issue when installing from master branch

### ISSUE THREAD

**Issue by cylldby** [cloudera/dbt-hive#91]
Hello !

I'm trying to install the package directly from the GitHub repository in order to get the most up-to-date work (mainly [this commit](https://github.com/cloudera/dbt-hive/pull/89)) with the following command:

`pip install git+https://github.com/cloudera/dbt-hive.git`

Unfortunately I'm met with the error 

> error: can't copy 'dbt/adapters/hive/.env': doesn't exist or not a regular file

It seems to be related to the fact that in `setup.py` there is `data_files=[('', ['dbt/adapters/hive/.env'])],`
while this file doesn't exist at the specified location in the master branch.

Would it be possible to add an empty folder at this location to fix this ?

Thank you for your support !

**Comment by cylldby** [comment]
Strange behaviour actually:
when cloning the repository locally, and then installing locally, there is not problem at all

```bash
git clone https://github.com/cloudera/dbt-hive.git

pip install -e dbt-hive/
```

returns `Successfully installed dbt-hive-1.3.1`

**Comment by tovganesh** [comment]
@cylldby you may copy https://github.com/cloudera/dbt-hive/blob/main/.env_example in the above location 
and use usage_tracking: false in your dbt profile

**Comment by cylldby** [comment]
Thank you for everything !
