### ISSUE TITLE
hive parameters not settable

### ISSUE THREAD

**Issue by bijzz** [cloudera/dbt-hive#93]
Is it possible to set hive parameters like `set hive.tez.container.size=8192` for all connections or per model?

I added the statement in a dbt macro like

```

{% macro hive_settings() %}

{% set sql %}
    set hive.tez.container.size=8192
{% endset %}

{% do run_query(sql) %}

{% do log("Hive settings applied", info=True) %}
{% endmacro %}
```

But runnning it `dbt run-operation hive_settings` ends in

```
Running with dbt=1.3.2
Hive settings applied
Encountered an error while running operation: Runtime Error
Runtime Error
Unable to establish connection to Hive server: Error while compiling statement: FAILED: ParseException line4:8 cannot recognize input near 'set' 'hive' '.' in statement
```

Additionally, it would be nice to set them via `profiles.yml` similiar to the `server_side_parameters` in the dbt-spark module, see https://docs.getdbt.com/reference/warehouse-setups/spark-setup#odbc.

**Comment by tovganesh** [comment]
@bijzz please see this https://github.com/cloudera/dbt-hive/issues/85

You can use pre-hooks to use hive parameters.

**Comment by bijzz** [comment]
Thanks, pre-hooks work after building the package from latest source.
