### ISSUE TITLE
Cannot create external tables with partitions and non-default file format

### ISSUE THREAD

**Issue by jazumaquero** [cloudera/dbt-hive#99]
Hi,

Thanks for developing this dbt adapter for Hive,

I have being suffering some issues while trying to create external partitions tables with some specific file formats , for instance using next configuration
```jinja2
{{
  config(
    materialized="incremental",
    incremental_strategy= "insert_overwrite",
    external=True,
    file_format= "orc",
    partition_by=["some colum"],
  ) 
}}
```
Looks like this issue is happening because when the file format is added when table is being created (https://github.com/cloudera/dbt-hive/blob/f293ba97eaea824604bd83fe684d92b84f67d4d9/dbt/include/hive/macros/adapters.sql#L125-L137)

This is not consistent with Hive [CREATE TABLE definition](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-CreateTableCreate/Drop/TruncateTable) that expect STORED AS TO BE after partitioning and before location.

So that, I guess it should be something like following
```jinja2
    {% else %}
      create {% if is_external == true -%}external{%- endif %} table {{ relation }}
    {% endif %}
    {{ options_clause() }}
    {{ partition_cols(label="partitioned by") }}
    {{ clustered_cols(label="clustered by") }}
    {{ file_format_clause() }}
    {{ location_clause() }}
    {{ comment_clause() }}
    {{ properties_clause(_properties) }}
    as
      {{ sql }}
```

Best Regards,
Zuma

**Comment by niteshy** [comment]
This is resolved in #96
